# This workflow builds and runs GTest unit tests
name: GTest Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release
  BUILD_TEST: ON

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=${{env.BUILD_TEST}}

      - name: Build project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}}
